/** "Who in this room is most likely to..." Keep them kind; the point is laughter, not a grudge. */
export const PROMPTS: readonly string[] = [
  "survive a zombie apocalypse",
  "become famous for something odd",
  "forget their own birthday",
  "adopt five cats by accident",
  "win a hot-dog eating contest",
  "get lost in their own neighbourhood",
  "start a band tomorrow",
  "talk their way out of a parking ticket",
  "cry at a commercial",
  "eat dessert before dinner",
  "sleep through an earthquake",
  "become a game show host",
  "laugh at the worst possible moment",
  "move to another country on a whim",
  "win an argument with a toddler",
  "secretly be a superhero",
  "text back three days later",
  "run a marathon without training",
  "own a pet lizard",
  "befriend a stranger on a plane",
  "trip over nothing",
  "invent a new holiday",
  "give the best advice",
  "sing in the shower loudly",
  "still be awake at 4 a.m.",
  "bring snacks to everything",
  "become a millionaire by 40",
  "lose their keys twice in one day",
  "dance on a table",
  "write a bestselling novel",
  "be late to their own wedding",
  "win a staring contest",
  "become a wildlife documentary narrator",
  "eat the last slice without asking",
  "know a random fact about everything",
  "get kicked out of a library for laughing",
];
